# Generated by Django 4.1.4 on 2022-12-08 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nurodykite kategorijos pavadinimą', max_length=100, verbose_name='Pavadinimas')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kategorija',
                'verbose_name_plural': 'Kategorijos',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Užrašo pavadinimas', max_length=100, verbose_name='Pavadinimas')),
                ('content', models.TextField(help_text='Čia rašykite norimą išsaugoti informaciją', max_length=1000, verbose_name='Užrašo turinys')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(default='default.png', upload_to='note_pics')),
                ('category', models.ManyToManyField(help_text='Pasirinkite įrašo kategorijas', to='notebook.category')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Užrašas',
                'verbose_name_plural': 'Užrašai',
            },
        ),
    ]
